[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.13.0"
gdk-pixbuf = "0.15.11"

[dependencies.glib]
version = "0.15.12"
features = ["v2_66"]

[dependencies.gio]
version = "0.15.12"
features = ["v2_66"]
